galaxy_info:
  role_name: docker-traefik
  author: Olivier Pichon <op@united-asian.com>
  description: Installs traefik proxy and other useful services as docker containers
  company: United Asian Management Limited

  license: MIT

  min_ansible_version: 1.2

  platforms:

  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags:
    - apt

dependencies: []
